import {supabase} from './supabase.js';
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null?'':new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v));
async function init(){
 const host=document.querySelector('.mz-feed-body');if(!host)return;
 const section=document.createElement('section');section.className='bo-card bo-section';section.style.marginTop='16px';section.innerHTML='<div class="bo-section-head"><h2>Ofertas cerca de ti</h2><a href="ofertas.html">Ver todas</a></div><div class="bo-offer-grid" id="homeOfferGrid"><div class="bo-loading">Cargando ofertas…</div></div>';host.appendChild(section);
 try{const {data,error}=await supabase.from('ofertas_negocios').select('*').eq('estado','publicada').eq('activa',true).order('aprobado_en',{ascending:false}).limit(4);if(error)throw error;const ids=[...new Set((data||[]).map(x=>x.comercio_id).filter(Boolean))];let bm=new Map();if(ids.length){const {data:b}=await supabase.from('negocios').select('id,nombre_comercial,slug,logo_url').in('id',ids);(b||[]).forEach(x=>bm.set(x.id,x))}document.querySelector('#homeOfferGrid').innerHTML=data?.length?data.map(o=>{const b=bm.get(o.comercio_id)||{};return `<article class="bo-offer-card">${o.imagen_url?`<img class="bo-offer-image" src="${esc(o.imagen_url)}">`:'<div class="bo-offer-placeholder"><i class="ti ti-tag"></i></div>'}<div class="bo-offer-body"><div class="bo-business-line">${esc(b.nombre_comercial||'Negocio MiZona')}</div><h3>${esc(o.titulo)}</h3><div class="bo-price-row"><span class="current">${money(o.precio_oferta??o.precio_normal)||esc(o.descuento_texto||'Oferta')}</span></div><div class="bo-offer-actions"><a href="oferta.html?id=${o.id}">Ver oferta</a><a href="negocio-publico.html?slug=${encodeURIComponent(b.slug||'')}">Ver negocio</a></div></div></article>`}).join(''):'<div class="bo-empty" style="grid-column:1/-1;padding:18px">Todavía no hay ofertas publicadas en tu zona.</div>'}catch(e){section.remove()}
}
init();
