import { supabase, getCurrentUser } from './supabase.js';
import { getStoredNearbyLocation, requestNearbyLocation } from './nearby-location.js';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v==null||v===''?'':new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(Number(v));
let user=null,business=null,memberships=[],offers=[],services=[],photos=[];
const root=$('#businessPanelRoot');
function alertBox(msg,type='info'){const e=$('#panelStatus');if(!e)return alert(msg);e.textContent=msg;e.className=`bo-status show ${type}`;setTimeout(()=>e.classList.remove('show'),4500)}
async function upload(file,prefix){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${user.id}/${prefix}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('negocios').upload(path,file,{upsert:true});if(error)throw error;return supabase.storage.from('negocios').getPublicUrl(path).data.publicUrl;}
function statusBadge(s){const labels={borrador:'Borrador',pendiente:'Pendiente',publicada:'Publicada',rechazada:'Rechazada',pausada:'Pausada',vencida:'Vencida'};return `<span class="bo-badge ${s}">${labels[s]||esc(s)}</span>`}
function requestView(req){
  if(req) return `<div class="bo-request-shell"><section class="bo-card bo-request-intro"><h1>Solicitud de negocio</h1><p>Tu solicitud está en revisión. Cuando sea aprobada, MiZona creará automáticamente tu página pública y habilitará el panel privado.</p><div class="bo-progress"><div class="active">1. Solicitud enviada</div><div class="${req.estado==='aprobada'?'active':''}">2. Revisión</div><div>3. Página publicada</div></div></section><section class="bo-card bo-section"><div class="bo-section-head"><h2>${esc(req.nombre_comercial)}</h2><span class="bo-badge ${req.estado==='rechazada'?'rejected':'pending'}">${esc(req.estado)}</span></div><p class="bo-about">${esc(req.descripcion||'')}</p>${req.motivo_revision?`<div class="bo-status show ${req.estado==='rechazada'?'error':'info'}">${esc(req.motivo_revision)}</div>`:''}</section></div>`;
  return `<div class="bo-request-shell"><section class="bo-card bo-request-intro"><h1>Crea la página de tu negocio</h1><p>Solicita una cuenta comercial. Después de la revisión administrativa, tendrás una página pública para clientes y un panel privado para administrarla.</p><div class="bo-progress"><div class="active">1. Completa tus datos</div><div>2. Revisión de MiZona</div><div>3. Página pública</div></div></section><form class="bo-card bo-section" id="businessRequestForm"><div class="bo-section-head"><h2>Datos del negocio</h2></div><div class="bo-form-grid">
  <div class="bo-field"><label>Nombre comercial</label><input class="bo-input" name="nombre_comercial" required maxlength="100"></div>
  <div class="bo-field"><label>Categoría</label><select class="bo-select" name="categoria" required><option value="">Seleccionar</option><option>comida</option><option>ferreteria</option><option>salud</option><option>belleza</option><option>servicios</option><option>hogar</option><option>mascotas</option><option>otros</option></select></div>
  <div class="bo-field"><label>Tipo</label><select class="bo-select" name="tipo_persona"><option value="persona_natural">Persona natural</option><option value="empresa">Empresa</option><option value="organizacion">Organización</option></select></div>
  <div class="bo-field"><label>Tipo de documento</label><select class="bo-select" name="documento_tipo"><option value="ruc">RUC</option><option value="dni">DNI</option><option value="ce">Carné de extranjería</option><option value="otro">Otro</option></select></div><div class="bo-field"><label>Número de documento</label><input class="bo-input" name="documento_numero" maxlength="20"></div>
  <div class="bo-field"><label>Distrito</label><input class="bo-input" name="distrito" required></div><div class="bo-field"><label>Zona o urbanización</label><input class="bo-input" name="zona"></div>
  <div class="bo-field"><label>WhatsApp</label><input class="bo-input" name="whatsapp" type="tel"></div><div class="bo-field"><label>Correo comercial</label><input class="bo-input" name="correo_comercial" type="email"></div>
  <div class="bo-field full"><label>Dirección comercial</label><input class="bo-input" name="direccion"></div>
  <div class="bo-field full"><label>Descripción</label><textarea class="bo-textarea" name="descripcion" required maxlength="700"></textarea></div>
  <div class="bo-field full"><label>Logotipo opcional</label><div class="bo-file"><i class="ti ti-photo"></i><span>Seleccionar imagen</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"></div></div>
  </div><div class="bo-form-actions"><button class="bo-primary-btn" type="submit"><i class="ti ti-send"></i> Enviar solicitud</button><a class="bo-ghost-btn" href="index.html">Cancelar</a></div><div class="bo-status" id="requestStatus"></div></form></div>`;
}
function renderPanel(){const activityBars=(offers.length?offers.slice(0,12).map(o=>Math.max(8,Math.min(100,Number(o.vistas||0)))):[8,8,8,8]);root.innerHTML=`<div class="bo-panel-layout"><aside class="bo-card bo-panel-nav"><div class="bo-panel-business">${business.logo_url?`<img src="${esc(business.logo_url)}">`:'<div class="bo-side-logo"></div>'}<div><strong>${esc(business.nombre_comercial)}</strong><small>${esc(business.categoria)}</small></div></div>
  ${[['summary','ti-layout-dashboard','Resumen'],['info','ti-building-store','Información'],['offers','ti-tag','Ofertas'],['services','ti-tool','Servicios'],['photos','ti-photo','Fotos']].map(([id,ic,l],i)=>`<button class="bo-panel-tab ${i===0?'active':''}" data-tab="${id}"><i class="ti ${ic}"></i>${l}</button>`).join('')}</aside>
  <section class="bo-panel-content"><div class="bo-status" id="panelStatus"></div>
  <div class="bo-panel-view active" data-view="summary"><div class="bo-panel-heading"><div><h1>${esc(business.nombre_comercial)}</h1><p style="color:#65758B">Panel privado del negocio</p></div><a class="bo-primary-btn" href="negocio-publico.html?slug=${encodeURIComponent(business.slug)}"><i class="ti ti-external-link"></i> Ver página pública</a></div><div class="bo-stat-grid"><div class="bo-card bo-stat-card"><span>Ofertas publicadas</span><strong id="statPublished">0</strong><small>Visibles para clientes</small></div><div class="bo-card bo-stat-card"><span>Pendientes</span><strong id="statPending">0</strong><small>En revisión</small></div><div class="bo-card bo-stat-card"><span>Servicios</span><strong id="statServices">0</strong><small>Activos</small></div><div class="bo-card bo-stat-card"><span>Fotos</span><strong id="statPhotos">0</strong><small>En galería</small></div></div><div class="bo-dashboard-grid"><section class="bo-card bo-section"><div class="bo-section-head"><h2>Vistas por oferta</h2></div><div class="bo-chart-placeholder">${activityBars.map(h=>`<span style="height:${h}%"></span>`).join('')}</div></section><section class="bo-card bo-section"><div class="bo-section-head"><h2>Acciones rápidas</h2></div><div class="bo-activity-list"><button class="bo-primary-btn" data-go="offers">Publicar oferta</button><button class="bo-secondary-btn" data-go="services">Agregar servicio</button><button class="bo-secondary-btn" data-go="photos">Subir fotos</button><button class="bo-secondary-btn" data-go="info">Editar información</button></div></section></div></div>
  <div class="bo-panel-view" data-view="info"><div class="bo-panel-heading"><h2>Información del negocio</h2></div><form class="bo-card bo-section" id="businessInfoForm"><div class="bo-form-grid"><div class="bo-field"><label>Nombre comercial</label><input class="bo-input" name="nombre_comercial" value="${esc(business.nombre_comercial)}" required></div><div class="bo-field"><label>Categoría</label><input class="bo-input" name="categoria" value="${esc(business.categoria)}"></div><div class="bo-field"><label>Distrito</label><input class="bo-input" name="distrito" value="${esc(business.distrito||'')}"></div><div class="bo-field"><label>Zona</label><input class="bo-input" name="zona" value="${esc(business.zona||'')}"></div><div class="bo-field"><label>WhatsApp</label><input class="bo-input" name="whatsapp" value="${esc(business.whatsapp||'')}"></div><div class="bo-field"><label>Teléfono</label><input class="bo-input" name="telefono" value="${esc(business.telefono||'')}"></div><div class="bo-field full"><label>Dirección pública</label><input class="bo-input" name="direccion_publica" value="${esc(business.direccion_publica||'')}"></div><div class="bo-field full"><label>Descripción</label><textarea class="bo-textarea" name="descripcion">${esc(business.descripcion||'')}</textarea></div><div class="bo-field"><label>Nuevo logo</label><input class="bo-input" name="logo" type="file" accept="image/*"></div><div class="bo-field"><label>Nueva portada</label><input class="bo-input" name="portada" type="file" accept="image/*"></div></div><div class="bo-form-actions"><button class="bo-primary-btn" type="submit">Guardar cambios</button></div></form></div>
  <div class="bo-panel-view" data-view="offers"><div class="bo-panel-heading"><h2>Mis ofertas</h2></div><form class="bo-card bo-section" id="offerForm"><div class="bo-section-head"><h2>Nueva oferta</h2></div><div class="bo-form-grid"><div class="bo-field"><label>Título</label><input class="bo-input" name="titulo" required></div><div class="bo-field"><label>Categoría</label><select class="bo-select" name="categoria"><option>comida</option><option>ferreteria</option><option>salud</option><option>belleza</option><option>servicios</option><option>hogar</option><option>mascotas</option><option>otros</option></select></div><div class="bo-field"><label>Precio normal</label><input class="bo-input" name="precio_normal" type="number" step="0.01"></div><div class="bo-field"><label>Precio de oferta</label><input class="bo-input" name="precio_oferta" type="number" step="0.01"></div><div class="bo-field"><label>Stock</label><input class="bo-input" name="stock" type="number"></div><div class="bo-field"><label>Vence</label><input class="bo-input" name="vence_en" type="datetime-local"></div><div class="bo-field full"><label>Descripción</label><textarea class="bo-textarea" name="descripcion"></textarea></div><div class="bo-field full"><label>Condiciones</label><textarea class="bo-textarea" name="condiciones"></textarea></div><div class="bo-field"><label>Imagen</label><input class="bo-input" name="imagen" type="file" accept="image/*"></div><div class="bo-field"><label><input name="permite_cupon" type="checkbox"> Permitir cupón</label><input class="bo-input" name="max_cupones" type="number" placeholder="Cantidad máxima"></div></div><div class="bo-form-actions"><button class="bo-secondary-btn" name="action" value="draft" type="submit">Guardar borrador</button><button class="bo-primary-btn" name="action" value="review" type="submit">Enviar a revisión</button></div></form><section class="bo-card bo-section" style="margin-top:14px"><div class="bo-section-head"><h2>Ofertas creadas</h2></div><div class="bo-offer-admin-list" id="offerList"></div></section></div>
  <div class="bo-panel-view" data-view="services"><div class="bo-panel-heading"><h2>Servicios y productos</h2></div><form class="bo-card bo-section" id="serviceForm"><div class="bo-form-grid"><div class="bo-field"><label>Nombre</label><input class="bo-input" name="titulo" required></div><div class="bo-field"><label>Precio desde</label><input class="bo-input" name="precio_desde" type="number" step="0.01"></div><div class="bo-field full"><label>Descripción</label><textarea class="bo-textarea" name="descripcion"></textarea></div></div><div class="bo-form-actions"><button class="bo-primary-btn" type="submit">Agregar servicio</button></div></form><section class="bo-card bo-section" style="margin-top:14px"><div id="serviceList"></div></section></div>
  <div class="bo-panel-view" data-view="photos"><div class="bo-panel-heading"><h2>Galería</h2></div><form class="bo-card bo-section" id="photoForm"><div class="bo-field"><label>Subir fotografía</label><input class="bo-input" name="photo" type="file" accept="image/*" required></div><div class="bo-field"><label>Descripción</label><input class="bo-input" name="descripcion"></div><div class="bo-form-actions"><button class="bo-primary-btn" type="submit">Subir foto</button></div></form><section class="bo-card bo-section" style="margin-top:14px"><div class="bo-photo-grid" id="photoList"></div></section></div>
  </section></div>`;bindPanel();renderLists();}
function selectTab(id){$$('.bo-panel-tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===id));$$('.bo-panel-view').forEach(v=>v.classList.toggle('active',v.dataset.view===id));}
function renderLists(){
  $('#statPublished').textContent=offers.filter(o=>o.estado==='publicada').length;$('#statPending').textContent=offers.filter(o=>o.estado==='pendiente').length;$('#statServices').textContent=services.filter(s=>s.activo).length;$('#statPhotos').textContent=photos.length;
  $('#offerList').innerHTML=offers.length?offers.map(o=>`<article class="bo-offer-admin-row">${o.imagen_url?`<img src="${esc(o.imagen_url)}">`:'<div class="bo-side-logo"></div>'}<div><h3>${esc(o.titulo)}</h3><p>${money(o.precio_oferta??o.precio_normal)} · ${esc(o.motivo_revision||'')}</p></div><div class="bo-offer-admin-actions">${statusBadge(o.estado)}${o.estado==='borrador'||o.estado==='rechazada'?`<button class="bo-secondary-btn" data-send-review="${o.id}">Enviar a revisión</button>`:''}${o.estado==='publicada'?`<button class="bo-ghost-btn" data-pause="${o.id}">Pausar</button>`:''}${['borrador','rechazada'].includes(o.estado)?`<button class="bo-danger-btn" data-delete-offer="${o.id}">Eliminar</button>`:''}</div></article>`).join(''):'<div class="bo-empty">Aún no creaste ofertas.</div>';
  $('#serviceList').innerHTML=services.length?services.map(s=>`<div class="bo-admin-row"><div><h3>${esc(s.titulo)}</h3><p>${esc(s.descripcion||'')} ${s.precio_desde!=null?`· Desde ${money(s.precio_desde)}`:''}</p></div><div><button class="bo-danger-btn" data-delete-service="${s.id}">Eliminar</button></div></div>`).join(''):'<div class="bo-empty">Aún no agregaste servicios.</div>';
  $('#photoList').innerHTML=photos.length?photos.map(p=>`<div style="position:relative"><img src="${esc(p.url)}"><button class="bo-icon-btn" data-delete-photo="${p.id}" style="position:absolute;right:6px;top:6px"><i class="ti ti-trash"></i></button></div>`).join(''):'<div class="bo-empty" style="grid-column:1/-1">Aún no agregaste fotos.</div>';
  bindListActions();
}
function bindPanel(){
  $$('[data-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.tab)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.go)));
  $('#businessInfoForm')?.addEventListener('submit',saveInfo);$('#offerForm')?.addEventListener('submit',saveOffer);$('#serviceForm')?.addEventListener('submit',saveService);$('#photoForm')?.addEventListener('submit',savePhoto);
}
async function saveInfo(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=new FormData(e.currentTarget),payload=Object.fromEntries(['nombre_comercial','categoria','distrito','zona','whatsapp','telefono','direccion_publica','descripcion'].map(k=>[k,String(f.get(k)||'').trim()||null]));const point=getStoredNearbyLocation()||await requestNearbyLocation({interactive:true});if(point){payload.latitud=Number(point.lat.toFixed(5));payload.longitud=Number(point.lng.toFixed(5));}const logo=await upload(f.get('logo')?.size?f.get('logo'):null,'logo'),portada=await upload(f.get('portada')?.size?f.get('portada'):null,'portada');if(logo)payload.logo_url=logo;if(portada)payload.portada_url=portada;const {data,error}=await supabase.from('negocios').update(payload).eq('id',business.id).select().single();if(error)throw error;business=data;alertBox('Información actualizada.','ok');}catch(err){alertBox(err.message,'error')}finally{b.disabled=false}}
async function saveOffer(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=new FormData(e.currentTarget),normal=Number(f.get('precio_normal')||0)||null,promo=Number(f.get('precio_oferta')||0)||null,img=await upload(f.get('imagen')?.size?f.get('imagen'):null,'oferta');const payload={comercio_id:business.id,titulo:String(f.get('titulo')).trim(),categoria:f.get('categoria'),descripcion:String(f.get('descripcion')||'').trim()||null,condiciones:String(f.get('condiciones')||'').trim()||null,precio_normal:normal,precio_oferta:promo,porcentaje_descuento:normal&&promo?Math.max(0,Math.round((1-promo/normal)*100)):null,stock:f.get('stock')?Number(f.get('stock')):null,vence_en:f.get('vence_en')?new Date(f.get('vence_en')).toISOString():null,imagen_url:img,permite_cupon:f.get('permite_cupon')==='on',max_cupones:f.get('max_cupones')?Number(f.get('max_cupones')):null,distrito:business.distrito,latitud:business.latitud||null,longitud:business.longitud||null,estado:b.value==='review'?'pendiente':'borrador',activa:false};const {error}=await supabase.from('ofertas_negocios').insert(payload);if(error)throw error;e.currentTarget.reset();await loadData();alertBox(b.value==='review'?'Oferta enviada a revisión.':'Borrador guardado.','ok')}catch(err){alertBox(err.message,'error')}finally{b.disabled=false}}
async function saveService(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=new FormData(e.currentTarget);const {error}=await supabase.from('negocio_servicios').insert({negocio_id:business.id,titulo:String(f.get('titulo')).trim(),descripcion:String(f.get('descripcion')||'').trim()||null,precio_desde:f.get('precio_desde')?Number(f.get('precio_desde')):null});if(error)throw error;e.currentTarget.reset();await loadData();alertBox('Servicio agregado.','ok')}catch(err){alertBox(err.message,'error')}finally{b.disabled=false}}
async function savePhoto(e){e.preventDefault();const b=e.submitter;b.disabled=true;try{const f=new FormData(e.currentTarget),url=await upload(f.get('photo'),'foto');const {error}=await supabase.from('negocio_fotos').insert({negocio_id:business.id,url,descripcion:String(f.get('descripcion')||'').trim()||null});if(error)throw error;e.currentTarget.reset();await loadData();alertBox('Foto agregada.','ok')}catch(err){alertBox(err.message,'error')}finally{b.disabled=false}}
function bindListActions(){
  $$('[data-send-review]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.rpc('enviar_oferta_revision',{p_oferta_id:b.dataset.sendReview});if(error)return alertBox(error.message,'error');await loadData();alertBox('Oferta enviada a revisión.','ok')});
  $$('[data-pause]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('ofertas_negocios').update({estado:'pausada',activa:false}).eq('id',b.dataset.pause);if(error)return alertBox(error.message,'error');await loadData()});
  $$('[data-delete-offer]').forEach(b=>b.onclick=async()=>{if(!confirm('¿Eliminar esta oferta?'))return;const {error}=await supabase.from('ofertas_negocios').delete().eq('id',b.dataset.deleteOffer);if(error)return alertBox(error.message,'error');await loadData()});
  $$('[data-delete-service]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('negocio_servicios').delete().eq('id',b.dataset.deleteService);if(error)return alertBox(error.message,'error');await loadData()});
  $$('[data-delete-photo]').forEach(b=>b.onclick=async()=>{const {error}=await supabase.from('negocio_fotos').delete().eq('id',b.dataset.deletePhoto);if(error)return alertBox(error.message,'error');await loadData()});
}
async function loadData(){const [o,s,p]=await Promise.all([supabase.from('ofertas_negocios').select('*').eq('comercio_id',business.id).order('created_at',{ascending:false}),supabase.from('negocio_servicios').select('*').eq('negocio_id',business.id).order('orden'),supabase.from('negocio_fotos').select('*').eq('negocio_id',business.id).order('orden')]);if(o.error)throw o.error;if(s.error)throw s.error;if(p.error)throw p.error;offers=o.data||[];services=s.data||[];photos=p.data||[];if($('#offerList'))renderLists();}
async function init(){try{user=await getCurrentUser();if(!user){location.href='login.html?next=negocio.html';return}const {data:mem,error:me}=await supabase.from('negocio_miembros').select('negocio_id,rol').eq('usuario_id',user.id).eq('activo',true);if(me)throw me;memberships=mem||[];if(!memberships.length){const {data:req,error}=await supabase.from('solicitudes_negocio').select('*').eq('solicitante_id',user.id).order('creado_en',{ascending:false}).limit(1).maybeSingle();if(error)throw error;root.innerHTML=requestView(req);$('#businessRequestForm')?.addEventListener('submit',async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;const box=$('#requestStatus');try{const f=new FormData(e.currentTarget),logo=await upload(f.get('logo')?.size?f.get('logo'):null,'solicitud-logo');const payload={solicitante_id:user.id,nombre_comercial:String(f.get('nombre_comercial')).trim(),categoria:f.get('categoria'),tipo_persona:f.get('tipo_persona'),documento_tipo:String(f.get('documento_numero')||'').trim()?f.get('documento_tipo'):null,documento_numero:String(f.get('documento_numero')||'').trim()||null,descripcion:String(f.get('descripcion')).trim(),distrito:String(f.get('distrito')).trim(),zona:String(f.get('zona')||'').trim()||null,direccion:String(f.get('direccion')||'').trim()||null,whatsapp:String(f.get('whatsapp')||'').trim()||null,correo_comercial:String(f.get('correo_comercial')||'').trim()||null,logo_url:logo};const point=getStoredNearbyLocation()||await requestNearbyLocation({interactive:true});if(point){payload.latitud=Number(point.lat.toFixed(5));payload.longitud=Number(point.lng.toFixed(5));}const {error}=await supabase.from('solicitudes_negocio').insert(payload);if(error)throw error;location.reload()}catch(err){box.textContent=err.message;box.className='bo-status show error'}finally{b.disabled=false}});return}const chosen=localStorage.getItem('mizona_business_id');const id=memberships.some(m=>m.negocio_id===chosen)?chosen:memberships[0].negocio_id;localStorage.setItem('mizona_business_id',id);const {data,error}=await supabase.from('negocios').select('*').eq('id',id).single();if(error)throw error;business=data;await loadData();renderPanel()}catch(err){root.innerHTML=`<div class="bo-card bo-empty"><i class="ti ti-database-off"></i><strong>No se pudo abrir el panel</strong><span>${esc(err.message)}</span><p>Ejecuta sql/fase4_negocios_ofertas.sql si todavía no instalaste esta fase.</p></div>`}}
init();
