import { supabase, getCurrentUser } from './supabase.js';
import { openOrRequestChat } from './chat-access.js';
const $=s=>document.querySelector(s);let user=null,userPoint=null,drivers=[],driverRow=null,watchId=null,lastPush=0;const markers=[];
const status=$('#rideStatus');
const map=L.map('rideMap',{zoomControl:true,scrollWheelZoom:true}).setView([-12.0464,-77.0428],13);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);
let userMarker=null,userCircle=null;
function show(t,type=''){status.className=`ride-status ${type}`;status.textContent=t}
function initials(v='U'){return String(v).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function distance(a,b){const R=6371000,toRad=x=>x*Math.PI/180,dLat=toRad(b.lat-a.lat),dLon=toRad(b.lng-a.lng),s=Math.sin(dLat/2)**2+Math.cos(toRad(a.lat))*Math.cos(toRad(b.lat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(s))}
function fmtDistance(m){return m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`}
function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Tu navegador no permite ubicación.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:30000})})}
function paintUser(point){userPoint=point;map.setView([point.lat,point.lng],15);userMarker&&map.removeLayer(userMarker);userCircle&&map.removeLayer(userCircle);userMarker=L.circleMarker([point.lat,point.lng],{radius:8,color:'#fff',weight:3,fillColor:'#185FA5',fillOpacity:1}).addTo(map).bindPopup('Tu ubicación aproximada');userCircle=L.circle([point.lat,point.lng],{radius:500,color:'#185FA5',weight:1,fillOpacity:.08}).addTo(map);$('#originText').value='Ubicación actual · GPS activo'}
function clearMarkers(){while(markers.length)map.removeLayer(markers.pop())}
function driverIcon(){return L.divIcon({html:'<div style="background:#185FA5;color:#fff;border-radius:50%;width:36px;height:36px;display:grid;place-items:center;border:3px solid #fff;box-shadow:0 3px 10px rgba(0,0,0,.25)">🚗</div>',iconSize:[36,36],iconAnchor:[18,18],className:''})}
async function contactDriver(id){try{await openOrRequestChat(id,{context:'Consulta desde MiZonaRide'});}catch(e){if(/verifica.*celular/i.test(e.message||''))location.href='verificar-telefono.html?next=ride.html';else alert(e.message||'No se pudo contactar al conductor.')}}
function renderDrivers(){clearMarkers();const sorted=drivers.map(d=>({...d,dist:userPoint?distance(userPoint,{lat:d.latitud,lng:d.longitud}):null})).sort((a,b)=>(a.dist??Infinity)-(b.dist??Infinity));$('#driverCount').textContent=String(sorted.length);$('#driverList').innerHTML=sorted.length?sorted.map(d=>`<article class="driver-item"><div class="driver-avatar">${d.avatar_url?`<img src="${esc(d.avatar_url)}" alt="">`:esc(initials(d.nombre_visible||d.username))}</div><div class="driver-main"><strong>${esc(d.nombre_visible||d.username||'Conductor')}</strong><small>${esc([d.vehiculo_marca,d.vehiculo_modelo,d.vehiculo_color].filter(Boolean).join(' · '))}</small><small>Placa pública: ${esc(d.placa_publica||'***')}</small></div><div><div class="driver-distance">${d.dist==null?'Distancia pendiente':fmtDistance(d.dist)}</div><button class="ride-btn secondary" data-contact-driver="${d.usuario_id}" type="button">Mensaje</button></div></article>`).join(''):'<div class="ride-status warning">No hay conductores verificados en línea cerca de ti en este momento.</div>';document.querySelectorAll('[data-contact-driver]').forEach(b=>b.addEventListener('click',()=>contactDriver(b.dataset.contactDriver)));for(const d of sorted){if(d.latitud==null||d.longitud==null)continue;const marker=L.marker([d.latitud,d.longitud],{icon:driverIcon()}).addTo(map).bindPopup(`<b>${esc(d.nombre_visible||d.username||'Conductor')}</b><br>${esc([d.vehiculo_marca,d.vehiculo_modelo,d.vehiculo_color].filter(Boolean).join(' · '))}<br>${d.dist==null?'':fmtDistance(d.dist)}`);marker.on('click',()=>{});markers.push(marker)}show(sorted.length?`${sorted.length} conductor${sorted.length===1?'':'es'} verificado${sorted.length===1?'':'s'} en línea.`:'No hay conductores en línea.','success')}
async function loadDrivers(){const {data,error}=await supabase.from('conductores_disponibles').select('*');if(error){show(error.message,'error');return;}drivers=data||[];renderDrivers()}
async function loadDriverState(){if(!user){$('#driverOnlineBox').innerHTML='<a class="ride-btn secondary" href="login.html?next=ride.html">Inicia sesión para conducir</a>';return;}const {data,error}=await supabase.from('conductores').select('*').eq('usuario_id',user.id).maybeSingle();if(error&&error.code!=='42P01'){return;}driverRow=data||null;if(!driverRow){$('#driverOnlineBox').innerHTML='<p style="font-size:11px;color:#64748b;margin:0">Todavía no tienes una cuenta de conductor aprobada.</p><a class="ride-btn primary" href="conductor.html">Solicitar verificación</a>';return;}const on=Boolean(driverRow.en_linea);$('#onlineDot').classList.toggle('on',on);$('#driverOnlineBox').innerHTML=`<div class="driver-online-line"><div><strong>${on?'Estás en línea':'Estás fuera de línea'}</strong><small style="display:block;color:#64748b;margin-top:3px">${esc([driverRow.vehiculo_marca,driverRow.vehiculo_modelo].filter(Boolean).join(' '))}</small></div><button class="ride-btn ${on?'danger':'primary'}" id="toggleOnline" type="button">${on?'Desconectarme':'Ponerme en línea'}</button></div><div class="ride-status ${on?'success':''}">${on?'Tu vehículo aparece en el mapa. Mantén MiZona abierta para actualizar la ubicación.':'Tu ubicación no se comparte mientras estás fuera de línea.'}</div>`;$('#toggleOnline').addEventListener('click',()=>setOnline(!on));if(on)startWatch()}
async function pushDriverLocation(point,online=true){const now=Date.now();if(online&&now-lastPush<8000)return;lastPush=now;const {error}=await supabase.rpc('mizona_actualizar_conductor_online',{p_en_linea:online,p_latitud:point?.lat??null,p_longitud:point?.lng??null,p_precision:point?.accuracy?Math.round(point.accuracy):null});if(error)throw error}
function startWatch(){if(watchId!=null||!navigator.geolocation)return;watchId=navigator.geolocation.watchPosition(async p=>{const point={lat:p.coords.latitude,lng:p.coords.longitude,accuracy:p.coords.accuracy};paintUser(point);try{await pushDriverLocation(point,true)}catch(e){show(e.message,'error')}},{enableHighAccuracy:true,maximumAge:5000,timeout:15000})}
function stopWatch(){if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null}}
async function setOnline(on){try{if(on){const p=await locate();paintUser(p);await pushDriverLocation(p,true);startWatch();}else{await pushDriverLocation(null,false);stopWatch();}await loadDriverState();await loadDrivers()}catch(e){show(e.message||'No se pudo actualizar el modo conductor.','error')}}
$('#refreshDrivers').addEventListener('click',async()=>{try{const p=await locate();paintUser(p)}catch{}await loadDrivers()});
$('#rideSearchForm').addEventListener('submit',async e=>{e.preventDefault();if(!userPoint){try{paintUser(await locate())}catch(err){show(err.message,'error');return;}}await loadDrivers();if(drivers.length)show(`Encontramos ${drivers.length} conductor${drivers.length===1?'':'es'} en línea. Puedes enviarle un mensaje privado.`,'success')});
user=await getCurrentUser();try{paintUser(await locate())}catch(e){show('Activa la ubicación para ordenar los vehículos por cercanía.','warning')}await Promise.all([loadDrivers(),loadDriverState()]);supabase.channel('ride-live').on('postgres_changes',{event:'*',schema:'public',table:'conductores'},()=>loadDrivers()).subscribe();setInterval(loadDrivers,15000);window.addEventListener('beforeunload',()=>{stopWatch()});
