import { supabase, getCurrentUser } from './supabase.js';
import { initMiZonaUI, escapeHtml, timeAgo } from './mizona-ui-v2.js';
import { openOrRequestChat } from './chat-access.js';
import { initNearbyExperience, getStoredNearbyLocation, getNearbyRadius, distanceMeters, formatDistance, requestNearbyLocation } from './nearby-location.js';

initMiZonaUI();
const list=document.querySelector('#requestsList');
const count=document.querySelector('#requestCount');
const searchInputs=[document.querySelector('#requestSearch'),document.querySelector('#requestSearchMobile')].filter(Boolean);
const category=document.querySelector('#requestCategory');
const dialog=document.querySelector('#requestDialog');
const form=document.querySelector('#requestForm');
const status=document.querySelector('#requestStatus');
let requests=[];let currentUser=null;let nearbyPoint=getStoredNearbyLocation();let profileDistrict=localStorage.getItem('mizona_zona')||'';
const normalize=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
function showStatus(message,isError=false){status.hidden=false;status.textContent=message;status.style.borderColor=isError?'var(--mz-red)':'var(--mz-green)';}
function money(value){const n=Number(value);return Number.isFinite(n)?`S/ ${n.toFixed(n%1?2:0)}`:'';}
function budget(item){if(item.presupuesto_desde!=null&&item.presupuesto_hasta!=null)return`${money(item.presupuesto_desde)} – ${money(item.presupuesto_hasta)}`;if(item.presupuesto_desde!=null)return`Desde ${money(item.presupuesto_desde)}`;if(item.presupuesto_hasta!=null)return`Hasta ${money(item.presupuesto_hasta)}`;return'Presupuesto por conversar';}
function urgencyLabel(v){return v==='urgente'?'Urgente':v==='hoy'?'Para hoy':'Normal';}
function dist(item){return nearbyPoint?distanceMeters(nearbyPoint,{lat:Number(item.latitud),lng:Number(item.longitud)}):NaN;}
function nearby(input){const radius=getNearbyRadius();const decorated=input.map(x=>({...x,_distanceMeters:dist(x)}));if(!nearbyPoint||radius===0)return decorated.sort((a,b)=>(a._distanceMeters||Infinity)-(b._distanceMeters||Infinity));const exact=decorated.filter(x=>Number.isFinite(x._distanceMeters)&&x._distanceMeters<=radius);const legacy=decorated.filter(x=>!Number.isFinite(x._distanceMeters)&&profileDistrict&&normalize(x.distrito)===normalize(profileDistrict));return exact.length?exact.sort((a,b)=>a._distanceMeters-b._distanceMeters):legacy;}
function render(){const term=searchInputs[0]?.value.trim().toLowerCase()||searchInputs[1]?.value.trim().toLowerCase()||'';const selected=category.value;const filtered=requests.filter(item=>{const h=`${item.titulo||''} ${item.categoria||''} ${item.descripcion||''} ${item.distrito||''}`.toLowerCase();return(!term||h.includes(term))&&(selected==='todas'||item.categoria===selected);});const visible=nearby(filtered);const radius=getNearbyRadius();count.textContent=nearbyPoint&&radius?`${visible.length} en ${radius>=1000?`${radius/1000} km`:`${radius} m`}`:`${visible.length} solicitudes`;
if(!visible.length){list.innerHTML=`<div class="mz-empty-state"><i class="ti ti-clipboard-off"></i><strong>No hay solicitudes dentro de ${radius>=1000?`${radius/1000} km`:`${radius} m`}.</strong><p>Amplía el radio o publica una necesidad para que profesionales cercanos puedan verla.</p><button class="mz-btn primary" data-expand-radius type="button">Ampliar a 1 km</button></div>`;list.querySelector('[data-expand-radius]')?.addEventListener('click',()=>window.MiZonaNearby?.setRadius(1000));return;}
list.innerHTML=visible.map(item=>{const own=currentUser?.id===item.usuario_id;const distance=Number.isFinite(item._distanceMeters)?`<span class="mz-distance-chip"><i class="ti ti-current-location"></i> A ${formatDistance(item._distanceMeters)}</span>`:`<span class="mz-distance-chip unknown"><i class="ti ti-map-pin"></i> ${escapeHtml(item.distrito||'Ubicación por confirmar')}</span>`;return`<article class="mz-feed-card"><div class="mz-feed-head"><div><span class="mz-tag ${item.urgencia==='urgente'?'reportada':'verificada'}">${escapeHtml(urgencyLabel(item.urgencia))}</span><h3>${escapeHtml(item.titulo)}</h3></div><strong>${escapeHtml(budget(item))}</strong></div><p>${escapeHtml(item.descripcion)}</p><div class="mz-feed-meta"><span><i class="ti ti-category"></i> ${escapeHtml(item.categoria)}</span>${distance}<span><i class="ti ti-clock"></i> ${timeAgo(item.created_at)}</span></div><div class="mz-feed-actions">${own?`<button class="mz-btn success sm" data-resolve="${item.id}"><i class="ti ti-check"></i> Marcar resuelta</button>`:`<button class="mz-btn primary sm" data-contact="${item.usuario_id}" data-title="${escapeHtml(item.titulo)}"><i class="ti ti-send"></i> Enviar propuesta</button>`}</div></article>`;}).join('');
list.querySelectorAll('[data-contact]').forEach(b=>b.addEventListener('click',()=>startConversation(b.dataset.contact,b.dataset.title)));list.querySelectorAll('[data-resolve]').forEach(b=>b.addEventListener('click',()=>resolveRequest(b.dataset.resolve)));}
async function queryRequests(){let result=await supabase.from('solicitudes_mizona').select('id,usuario_id,categoria,titulo,descripcion,distrito,presupuesto_desde,presupuesto_hasta,urgencia,estado,fecha_necesaria,created_at,latitud,longitud,precision_ubicacion').eq('estado','abierta').order('created_at',{ascending:false}).limit(150);if(result.error&&/latitud|longitud|precision_ubicacion/i.test(result.error.message||''))result=await supabase.from('solicitudes_mizona').select('id,usuario_id,categoria,titulo,descripcion,distrito,presupuesto_desde,presupuesto_hasta,urgencia,estado,fecha_necesaria,created_at').eq('estado','abierta').order('created_at',{ascending:false}).limit(150);return result;}
async function loadRequests(){currentUser=await getCurrentUser();if(!currentUser){list.innerHTML='<div class="mz-empty-state"><i class="ti ti-lock"></i><strong>Inicia sesión para ver las solicitudes.</strong><p>Por privacidad, las necesidades de los vecinos solo se muestran a usuarios registrados.</p><a class="mz-btn primary" href="login.html?next=solicitudes.html">Iniciar sesión</a></div>';count.textContent='Acceso privado';return;}const{data,error}=await queryRequests();if(error){list.innerHTML=`<div class="mz-empty-state"><i class="ti ti-database-exclamation"></i><strong>No se pudieron cargar las solicitudes.</strong><p>${escapeHtml(error.message)}</p></div>`;count.textContent='Error';return;}requests=data||[];render();}
async function openForm(){currentUser=await getCurrentUser();if(!currentUser){location.href=`login.html?next=${encodeURIComponent('solicitudes.html#publicar')}`;return;}status.hidden=true;try{const{data:p}=await supabase.from('perfiles').select('distrito').eq('id',currentUser.id).maybeSingle();profileDistrict=p?.distrito||profileDistrict;if(p?.distrito&&!form.elements.distrito.value)form.elements.distrito.value=p.distrito;const point=nearbyPoint||await requestNearbyLocation({interactive:true});if(point){form.elements.latitud.value=Number(point.lat.toFixed(3));form.elements.longitud.value=Number(point.lng.toFixed(3));}}catch{}dialog.showModal();}
async function startConversation(otherUserId,title){currentUser=currentUser||await getCurrentUser();if(!currentUser)return openForm();try{await openOrRequestChat(otherUserId,{context:`Propuesta para: ${title}`,notify:m=>window.mzToast?.(m)});}catch(error){window.mzToast?.(`No se pudo abrir el chat: ${error.message}`,'error');}}
async function resolveRequest(id){if(!confirm('¿Confirmas que esta solicitud ya fue resuelta?'))return;const{error}=await supabase.from('solicitudes_mizona').update({estado:'resuelta'}).eq('id',id).eq('usuario_id',currentUser.id);if(error)window.mzToast?.(error.message,'error');else{window.mzToast?.('Solicitud marcada como resuelta.');await loadRequests();}}
form.addEventListener('submit',async event=>{event.preventDefault();currentUser=currentUser||await getCurrentUser();if(!currentUser)return openForm();const submit=form.querySelector('[type="submit"]');submit.disabled=true;showStatus('Publicando solicitud...');try{const fd=new FormData(form);const point=nearbyPoint||getStoredNearbyLocation();const payload={usuario_id:currentUser.id,categoria:String(fd.get('categoria')||'Otros'),titulo:String(fd.get('titulo')||'').trim(),descripcion:String(fd.get('descripcion')||'').trim(),distrito:String(fd.get('distrito')||'').trim(),presupuesto_desde:fd.get('presupuesto_desde')?Number(fd.get('presupuesto_desde')):null,presupuesto_hasta:fd.get('presupuesto_hasta')?Number(fd.get('presupuesto_hasta')):null,urgencia:String(fd.get('urgencia')||'normal'),fecha_necesaria:fd.get('fecha_necesaria')||null,estado:'abierta',latitud:fd.get('latitud')?Number(fd.get('latitud')):(point?Number(point.lat.toFixed(3)):null),longitud:fd.get('longitud')?Number(fd.get('longitud')):(point?Number(point.lng.toFixed(3)):null),precision_ubicacion:'aprox_150m'};if(payload.titulo.length<5||payload.descripcion.length<10||!payload.distrito)throw new Error('Completa el título, la descripción y el distrito.');if(payload.presupuesto_desde!=null&&payload.presupuesto_hasta!=null&&payload.presupuesto_desde>payload.presupuesto_hasta)throw new Error('El presupuesto desde no puede ser mayor que el presupuesto hasta.');let{error}=await supabase.from('solicitudes_mizona').insert(payload);if(error&&/latitud|longitud|precision_ubicacion/i.test(error.message||'')){delete payload.latitud;delete payload.longitud;delete payload.precision_ubicacion;({error}=await supabase.from('solicitudes_mizona').insert(payload));}if(error)throw error;form.reset();dialog.close();window.mzToast?.('Solicitud publicada correctamente.');await loadRequests();}catch(error){showStatus(error.message||'No se pudo publicar la solicitud.',true);}finally{submit.disabled=false;}});
searchInputs.forEach(input=>input.addEventListener('input',()=>{searchInputs.forEach(other=>{if(other!==input)other.value=input.value;});render();}));category.addEventListener('change',render);document.querySelectorAll('#openRequestForm,#openRequestFormSecondary,#mobileRequestAdd').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();openForm();}));document.querySelectorAll('[data-close-dialog]').forEach(button=>button.addEventListener('click',()=>dialog.close()));window.addEventListener('mizona:location',e=>{nearbyPoint=e.detail.point;render();});window.addEventListener('mizona:radius-change',render);
if(location.hash==='#publicar')openForm();await initNearbyExperience({reason:'Activa tu ubicación para mostrar solicitudes vecinales que estén primero a 500 metros de ti.'});nearbyPoint=getStoredNearbyLocation();await loadRequests();
